/* Independent story reader. No artwork is embedded until the originals are reviewed. */
var Jungle = {
  episode:0,page:0,
  card:function(id){var c=DATA.jungle.characters.find(function(x){return x.id===id;});if(!c)return;Modal.open('<h2>'+esc(c.name)+' <small>'+esc(c.english)+'</small></h2>'+(c.img?'<img class="character-portrait" src="'+c.img+'" alt="'+esc(c.name)+'" onerror="this.hidden=true">':'')+'<p class="eyebrow">'+esc(c.kind)+' · '+esc(c.gender||'')+'</p><p>'+esc(c.role)+'</p><p class="mut">圖像製作指引：'+esc(c.visual||'按原著自然形態')+'</p><h3>問一問</h3><p>'+esc(c.question)+'</p><details><summary>睇答案及帶領提醒</summary><p>'+esc(c.answer)+'</p><p class="mut">'+esc(c.check)+'</p></details>');},
  open:function(i){if(!DATA.jungle.episodes[i])return;Jungle.episode=i;Jungle.page=0;Jungle.render();},
  move:function(delta){var ep=DATA.jungle.episodes[Jungle.episode];Jungle.page=Math.max(0,Math.min(ep.scenes.length-1,Jungle.page+delta));Jungle.render();},
  render:function(){var ep=DATA.jungle.episodes[Jungle.episode],s=ep.scenes[Jungle.page];Modal.open('<div class="story-reader"><p class="eyebrow">'+esc(ep.title)+' · '+(Jungle.page+1)+' / '+ep.scenes.length+'</p><h2>'+esc(s.title)+'</h2><p class="story-text">'+esc(s.text)+'</p><p class="mut">出場：'+s.cast.map(function(id){return esc(DATA.jungle.characters.find(function(c){return c.id===id;}).name);}).join('、')+'</p><h3>停一停，問一問</h3><p>'+esc(s.question)+'</p><details><summary>領袖答案與現實生活提醒</summary><p>'+esc(s.answer)+'</p><p class="safe">'+esc(s.lesson)+'</p></details><div class="quick"><button class="btn" onclick="Jungle.move(-1)" '+(Jungle.page===0?'disabled':'')+'>‹ 上一段</button><button class="btn gr" onclick="Jungle.move(1)" '+(Jungle.page===ep.scenes.length-1?'disabled':'')+'>下一段 ›</button><button class="btn" onclick="Modal.close()">收起故事</button></div><p class="mut">教學簡寫 · 文字可離線使用 · 圖卡待原圖核對後加入</p></div>');},
  view:function(){return '<section class="card"><a class="back" href="#book">‹ 手冊</a><h1>🌳 森林故事</h1><p>先認角色，再講故事，最後連回小隊生活。</p><div class="template-grid">'+DATA.jungle.episodes.map(function(ep,i){return '<article class="template-card"><span class="eyebrow">'+esc(ep.refs.join('／'))+'</span><h3>'+esc(ep.title)+'</h3><p>四段短故事 · 每段一個問題 · 領袖答案</p><div class="quick"><button class="btn gr" onclick="Jungle.open('+i+')">即開故事</button><span class="mut">文字工具卡，可按需要加入集會</span></div></article>';}).join('')+'</div></section><section class="card"><h2>11位角色：認人與配對</h2><p class="mut">撳角色先睇介紹，再展開答案。哈蒂與戴白祺可作延伸，不硬放入每段故事。</p><p class="mut" style="font-size:11px">頭像為 AI 繪製教學示意，非童軍總會官方原圖；角色文字介紹以官方版本為準。官方原圖見下方「你提供的圖卡」。</p><div class="template-grid">'+DATA.jungle.characters.map(function(c){return '<button class="btn character-card" onclick="Jungle.card(\''+c.id+'\')">'+(c.img?'<img src="'+c.img+'" alt="" loading="lazy" onerror="this.remove()">':'')+'<b>'+esc(c.name)+'</b><span>'+esc(c.english)+' · '+esc(c.kind)+'</span></button>';}).join('')+'</div></section><details class="card"><summary>故事來源及你提供的圖卡</summary><p>'+esc(DATA.jungle.sourceNote)+'</p>'+extBtn(DATA.jungle.source,false,'幼童軍支部：森林故事','角色及情節核對來源')+DATA.jungle.assets.map(function(a){return extBtn(a.url,false,a.label,a.status);}).join('')+'<p class="mut">目前只確認資源清單，未逐圖批准清晰度、去背或圖中文字。文字內容不依賴外部圖片載入。</p></details>';}
};
(function(){
  var route=App.route,book=App.vBook;
  App.vBook=function(){return '<section class="card"><h2>🌳 森林故事帶領</h2><p>角色介紹、四段故事及問題，撳開就可以講。</p><a class="btn gr" href="#jungle">開森林故事 →</a></section>'+book();};
  App.route=function(){if((location.hash||'').split('?')[0]!=='#jungle'){route();return;}App.tab='jungle';document.getElementById('view').innerHTML=Jungle.view();document.getElementById('view').style.paddingBottom='';var bar=document.getElementById('flowbar');bar.className='';bar.innerHTML='';document.querySelectorAll('#topnav a, #tabbar a').forEach(function(a){a.classList.toggle('cur',a.getAttribute('href')==='#jungle');});handleOffline();window.scrollTo(0,0);};
})();
(function(){
  var lead=App.vLead,detail=App.vMeetDetail;
  function shortcut(m){var i=m.tid==='c26'?0:m.tid==='c27'?1:-1;return i<0?'':'<section class="card"><h3>🌳 今場故事</h3><button class="btn gr" onclick="Jungle.open('+i+')">逐段講故事＋提問</button><a class="btn" href="#jungle">角色卡</a></section>';}
  App.vLead=function(){return shortcut(curMeet())+lead();};
  App.vMeetDetail=function(m){return shortcut(m)+detail(m);};
})();
