/* Shared material-only print workbench. Pure build; never changes a meeting. */
var MaterialDesk = {
 maxPages:250,
 kits:[
  {id:'uniform',title:'制服圖解與位置配對',group:'制服',scope:'制服手冊及生效修訂；真實肩章、新制核心章完整位置仍待核對。',open:function(){Uniform.open();},leader:function(){return Uniform.sheets(true);},pupil:function(){return Uniform.sheets(false);}},
  {id:'salutes',title:'手形、敬禮位置與情境',group:'禮儀',scope:'文字已核2026第五章；AI手形及自繪位置圖非官方照片，不按比例。',open:function(){SaluteLab.open();},leader:function(){return SaluteLab.sheets(true);},pupil:function(){return SaluteLab.sheets(false);}},
  {id:'tracking',title:'追蹤符號與三站活動',group:'技能',scope:'六款有來源描述的教學圖；六個符號名已核對官方工作紙，圖形屬自繪，原圖另開連結。',open:function(){TrackingKit.open();},leader:function(){return TrackingKit.sheets('guide');},shared:function(){return TrackingKit.sheets('cards');},pupil:function(){return TrackingKit.sheets('worksheet');}},
  {id:'commands',title:'六個集合口令',group:'禮儀',scope:'依已讀典禮附錄；傳統Alert／At Ease不混作中式隊列。',open:function(){Ceremony.open('commands');},leader:function(){return Ceremony.sheets('commands');}},
  {id:'howl',title:'團呼、隊形與角色提示',group:'禮儀',scope:'依2026第五章一般集會版本；呼號後立正，不混入2025比賽躍起要求。',open:function(){Ceremony.open('howl');},leader:function(){return Ceremony.sheets('howl');}},
  {id:'unfurl',title:'團旗展旗逐步卡',group:'禮儀',scope:'已備妥團旗的展旗程序；未含摺旗繫旗，不代替國旗／區旗程序。',open:function(){Ceremony.open('unfurl');},leader:function(){return Ceremony.sheets('unfurl');}},
  {id:'investiture',title:'宣誓逐步卡',group:'禮儀',scope:'程序依已讀典禮附錄，誓詞用現行文字；排練不等於正式宣誓。',open:function(){Ceremony.open('investiture');},leader:function(){return Ceremony.sheets('investiture');}},
  {id:'closing',title:'一般團集會開始與結束',group:'禮儀',scope:'只限一般團旗情境；散會不代替接送交接。',open:function(){Ceremony.open('closing');},leader:function(){return Ceremony.sheets('closing');}}
 ],
 get:function(id){return MaterialDesk.kits.find(function(k){return k.id===id;});},
 pages:function(html){return (html.match(/<section class="psheet(?:\s|\")/g)||[]).length;},
 count:function(n,max){if(typeof n!=='number'&&typeof n!=='string')return null;if(typeof n==='string'&&!n.trim())return null;n=Number(n);return Number.isInteger(n)&&n>=1&&n<=max?n:null;},
 validate:function(options){if(!options||!Array.isArray(options.ids)||options.ids.length===0)return {error:'請先選至少一套教材。'};if(options.ids.some(function(id){return !MaterialDesk.get(id);}))return {error:'包含未提供的教材，請重新選擇。'};var ids=Array.from(new Set(options.ids)),children=options.children!==false,n=MaterialDesk.count(options.copies,100),groups=MaterialDesk.count(options.groups,20);if(children&&(n===null||groups===null))return {error:'成員份數須為1–100整數；共用卡套數須為1–20整數。'};return {ids:ids,children:children,copies:children?n:1,groups:children?groups:1};},
 build:function(options){var config=MaterialDesk.validate(options);if(config.error)return config;var leaders=[],shared=[],pupils=[],summary=[];
 config.ids.forEach(function(id){var k=MaterialDesk.get(id),l=k.leader(),s=config.children&&k.shared?k.shared():'',p=config.children&&k.pupil?k.pupil():'';leaders.push(l);if(s)for(var i=0;i<config.groups;i++)shared.push(s);if(p)for(var j=0;j<config.copies;j++)pupils.push(p);summary.push({title:k.title,scope:k.scope,leader:MaterialDesk.pages(l),shared:MaterialDesk.pages(s)*config.groups,pupil:MaterialDesk.pages(p)*config.copies});});
 var child=shared.join('')+pupils.join(''),pages=1+MaterialDesk.pages(leaders.join(''))+MaterialDesk.pages(child)+(child?1:0);if(pages>MaterialDesk.maxPages)return {error:'本次將超過'+MaterialDesk.maxPages+'頁，請減少份數或分批選教材。'};
 var cover='<section class="psheet leader-sheet material-cover"><h2>教材出袋清單｜只含所選教材</h2><p>共'+pages+'頁（含本清單'+(child?'及派發分隔頁':'')+'）。領袖頁每套一份；'+(config.children?'成員紙每款'+config.copies+'份，共用卡每款'+config.groups+'套。':'本次只印領袖頁，不含共用卡及成員紙。')+'</p><table class="material-summary"><thead><tr><th>教材</th><th>領袖頁</th><th>共用卡頁</th><th>成員頁</th></tr></thead><tbody>'+summary.map(function(x){return '<tr><td>'+esc(x.title)+'</td><td>'+x.leader+'</td><td>'+x.shared+'</td><td>'+x.pupil+'</td></tr>';}).join('')+'</tbody></table><h3>帶走前確認</h3><ul><li>□ 所選圖卡及來源版本合適；未核項目另行確認。</li><li>□ 領袖答案留在分隔前，不派給成員；共用卡按組數剪好。</li><li>□ 每人紙筆及實體制服／旅巾／旗架等器材另備，紙包不包含器材。</li><li>□ 成人已確認場地、照顧範圍及停止條件；不能安全做動作時安排支援。</li></ul><h3>本次來源與適用界線</h3>'+summary.map(function(x){return '<p><b>'+esc(x.title)+'：</b>'+esc(x.scope)+'</p>';}).join('')+'<p>本包只整理教材，不是完整集會教案；五節帶法、點名與接送仍用所選集會出隊包。列印不代表備妥集會、完成考驗或頒章，不含團員名單及私人備忘。</p></section>';
 return {html:cover+leaders.join('')+(child?'<section class="psheet divider material-divider"><h2>以下才派給成員</h2><p>先分共用卡，再按人數分成員紙。前面的領袖答案不可混入。</p><p>共用卡是整組共用，不是每人一套；缺圖或缺頁請補印後再使用。</p></section>'+child:''),pages:pages,summary:summary};},
 open:function(){Modal.open('<h2>教材工作台｜選好，一次列印</h2><p>只打包你選的教材；如果要五節完整教案，仍用集會的「完整出隊包」。</p><form onsubmit="MaterialDesk.preview();return false"><div class="material-options">'+MaterialDesk.kits.map(function(k){return '<article><label><input type="checkbox" id="material-'+k.id+'"> <b>'+esc(k.title)+'</b></label><p>'+esc(k.scope)+'</p><p class="mut">領袖頁'+(k.shared?' · 共用卡':'')+(k.pupil?' · 成員紙':'')+'</p><button type="button" class="btn" onclick="MaterialDesk.inspect(\''+k.id+'\')">查看內容</button></article>';}).join('')+'</div><label class="field-label">成員紙每款份數<input id="material-copies" type="number" value="1" min="1" max="100" step="1"></label><label class="field-label">共用圖卡每款套數（按組數）<input id="material-groups" type="number" value="1" min="1" max="20" step="1"></label><label><input id="material-children" type="checkbox" checked onchange="MaterialDesk.toggle()"> 包含共用卡及成員紙（取消＝只印領袖頁）</label><div class="quick"><button class="btn gr" type="submit">產生所選教材預覽</button></div></form><p class="mut">上限250頁。預覽會列明實際頁數；勾選只在本頁暫存，重新載入會清除。不讀名單、不儲存個人成績、不改今場準備。</p>');MaterialDesk.restore();},
 draft:null,
 capture:function(){return {ids:MaterialDesk.kits.filter(function(k){return document.getElementById('material-'+k.id).checked;}).map(function(k){return k.id;}),copies:document.getElementById('material-copies').value,groups:document.getElementById('material-groups').value,children:document.getElementById('material-children').checked};},
 restore:function(){var d=MaterialDesk.draft;if(d){MaterialDesk.kits.forEach(function(k){document.getElementById('material-'+k.id).checked=d.ids.includes(k.id);});document.getElementById('material-copies').value=d.copies;document.getElementById('material-groups').value=d.groups;document.getElementById('material-children').checked=d.children;}MaterialDesk.toggle();},
 toggle:function(){var off=!document.getElementById('material-children').checked;document.getElementById('material-copies').disabled=off;document.getElementById('material-groups').disabled=off;},
 inspect:function(id){var k=MaterialDesk.get(id);if(!k)return;MaterialDesk.draft=MaterialDesk.capture();k.open();var el=document.getElementById('modal');if(el&&el.querySelector){var box=el.querySelector('.mbox');if(box)box.insertAdjacentHTML('afterbegin','<button class="btn" onclick="MaterialDesk.open()">回教材選擇（保留勾選）</button>');}},
 preview:function(){var d=MaterialDesk.capture(),result=MaterialDesk.build(d);if(result.error){toast(result.error);return false;}MaterialDesk.draft=d;Practical.printModal('所選教材｜'+result.pages+'頁',result.html);var el=document.getElementById('modal');if(el&&el.querySelector){var q=el.querySelector('.quick');if(q)q.insertAdjacentHTML('beforeend','<button class="btn" onclick="MaterialDesk.open()">返回修改教材與份數</button>');}return true;},
 panel:function(){return '<section class="card"><h2>教材工作台</h2><p>制服、敬禮、儀式及追蹤：自己選教材，領袖答案、共用卡及成員紙分區一次印。</p><button class="btn gr" onclick="MaterialDesk.open()">選教材・打包列印</button></section>';}
};
(function(){var book=App.vBook,sheets=App.vSheets;App.vBook=function(){return MaterialDesk.panel()+book();};App.vSheets=function(){return MaterialDesk.panel()+sheets();};})();
