/* Practical teaching layer: shared by preparation, live use, activity library and paper. */
var Practical = {
  persist:function(key,value){try{localStorage.setItem('cub_'+key,JSON.stringify(value));return true;}catch(e){toast('未能儲存：裝置儲存空間不可用，請先保留文字再試。');return false;}},
  meeting:function(tid){return DATA.meetings.find(function(m){return m.tid===tid;});},
  reader:{tid:'',index:0,reveal:false},
  summary:function(m){if(!m.practical)return '';return '<section class="card field-summary"><span class="eyebrow">實戰帶領包</span><h3>開場照讀</h3><p class="say">「'+esc(m.practical.opening)+'」</p><div class="quick"><button class="btn gr" onclick="Practical.open(\''+m.tid+'\')">分組・冷場・後備方案</button><button class="btn" onclick="Practical.quiz(\''+m.tid+'\')">即開問題卡</button>'+((m.practical.decks||[]).map(function(k){return '<button class="btn" onclick="Practical.deck(\''+k+'\')">'+esc(k==='troop'?'旅團身份卡':DATA.fieldDecks[k].title)+'</button>';}).join(''))+'</div></section>';},
  open:function(tid){var m=Practical.meeting(tid);if(!m||!m.practical)return;var p=m.practical;
    Modal.open('<h2>'+esc(m.n)+'｜實戰卡</h2><p class="say">「'+esc(p.opening)+'」</p><h3>先分組、再派物</h3><p>'+esc(p.distribute)+'</p><details open><summary>佢唔明，下一句點接？</summary><p>'+esc(p.confused)+'</p></details><details><summary>唔投入／唔想答</summary><p>'+esc(p.quiet)+'</p></details><details><summary>少人點玩</summary><p>'+esc(p.few)+'</p></details><details><summary>缺物資，點樣安全改</summary><p>'+esc(p.missing)+'</p></details><details><summary>只剩30分鐘</summary><ol>'+p.short.steps.map(function(x){return '<li><b>'+x.minutes+'分鐘：</b>'+esc(x.text)+'</li>';}).join('')+'</ol><p class="safe">'+esc(p.short.boundary)+'</p></details><details><summary>完場睇甚麼／來源與界線</summary><p>'+esc(m.evidence)+'</p><p>'+esc(m.gap)+'</p><p class="mut">'+esc(p.sourceNote)+'</p>'+extBtn(DATA.practicalSources.syllabus.url,false,'訓練綱要','正式要求依適用版本確認')+(p.sourceNote.indexOf('官方套包')>=0?extBtn(DATA.practicalSources.pack.url,false,'官方集會套包','活動點子參考，不限定APP編排'):'')+'</details><div class="quick"><button class="btn gr" onclick="Practical.quiz(\''+tid+'\')">用兩題檢查理解</button><button class="btn" onclick="Practical.print(\''+tid+'\')">印領袖實戰卡</button></div>');handleOffline();
  },
  quiz:function(tid){var m=Practical.meeting(tid);if(!m||!m.practical)return;Practical.reader={tid:tid,index:0,reveal:false};Practical.renderQuiz();},
  next:function(delta){var state=Practical.reader,m=Practical.meeting(state.tid);if(!m||!m.practical)return;state.index=Math.max(0,Math.min(m.practical.qa.length-1,state.index+delta));state.reveal=false;Practical.renderQuiz();},
  reveal:function(){Practical.reader.reveal=true;Practical.renderQuiz();},
  renderQuiz:function(){var state=Practical.reader,m=Practical.meeting(state.tid);if(!m||!m.practical)return;var q=m.practical.qa[state.index];Modal.open('<section class="field-question"><span class="eyebrow">'+esc(m.n)+' · 問題 '+(state.index+1)+' / '+m.practical.qa.length+'</span><h2>'+esc(q.q)+'</h2>'+(state.reveal?'<div class="field-answer"><b>領袖參考答案</b><p>'+esc(q.a)+'</p><small>接受有道理的等效答案；答對不等於已完成整項考驗。</small></div>':'<button class="btn gr" onclick="Practical.reveal()">聽完回答，再揭答案</button>')+'<div class="quick"><button class="btn" onclick="Practical.next(-1)" '+(state.index===0?'disabled':'')+'>‹ 上一題</button><button class="btn" onclick="Practical.next(1)" '+(state.index===m.practical.qa.length-1?'disabled':'')+'>下一題 ›</button><button class="btn" onclick="Practical.open(\''+m.tid+'\')">返實戰卡</button></div></section>');},
  troop:function(){var p=Store.get('troopProfile',{});return p&&typeof p==='object'?p:{};},
  troopFields:[['number','旅號'],['district','所屬區'],['region','所屬地域'],['sponsor','主辦機構']],
  getDeck:function(key){if(key!=='troop')return DATA.fieldDecks[key];var profile=Practical.troop();return {title:'我的旅團：四個身份資料',brief:'領袖先填真實旅團資料。每次一人拿一張名稱卡，配到旅號、區、地域、主辦機構，說出理由再換下一人；不跑、不搶卡。未填的欄位先向旅團核實，不猜答案。',source:'pack',cards:Practical.troopFields.map(function(f){return {front:f[1],back:typeof profile[f[0]]==='string'&&profile[f[0]].trim()?profile[f[0]]:'尚未填寫，請向旅團核實。'};})};},
  deck:function(key){var d=Practical.getDeck(key);if(!d)return;var source=DATA.practicalSources[d.source];Modal.open('<h2>'+esc(d.title)+'</h2><p class="field-brief">'+esc(d.brief)+'</p>'+(key==='troop'?'<button class="btn" onclick="Practical.editTroop()">填寫／修改旅團資料</button>':'')+'<div class="field-deck">'+d.cards.map(function(c){return '<details><summary>'+esc(c.front)+'</summary><p>'+esc(c.back)+'</p></details>';}).join('')+'</div><div class="quick"><button class="btn" onclick="Practical.printDeck(\''+key+'\',false)">印題面（無答案）</button><button class="btn" onclick="Practical.printDeck(\''+key+'\',true)">印領袖答案</button></div><p class="mut">文字卡可離線看。認識真實徽章或肩章仍須使用已核實實物／正式教材，不以文字卡代替圖樣觀察。</p>'+(source?extBtn(source.url,false,source.title,'要求／活動點子參考，短講及題卡另行整理') :''));handleOffline();},
  editTroop:function(){var p=Practical.troop();Modal.open('<h2>旅團資料</h2><p>只填公開旅團資料，不填團員姓名或家庭地址；保存在這部裝置。</p><form onsubmit="Practical.saveTroop();return false">'+Practical.troopFields.map(function(f){return '<label class="field-label">'+f[1]+'<input id="troop-'+f[0]+'" maxlength="120" value="'+esc(p[f[0]]||'')+'" autocomplete="off"></label>';}).join('')+'<button class="btn gr" type="submit">儲存並開身份卡</button></form>');},
  saveTroop:function(){var p={};Practical.troopFields.forEach(function(f){p[f[0]]=String(document.getElementById('troop-'+f[0]).value||'').trim().slice(0,120);});if(!Practical.persist('troopProfile',p))return false;Practical.deck('troop');return true;},
  printModal:function(title,html){PackPrint.activeTid=null;Modal.open('<h2>'+esc(title)+'</h2><p class="mut">獨立教材，列印不改今場準備或獎章狀態。</p><div class="quick"><button class="btn gr" onclick="window.print()">列印</button></div><div id="printarea">'+html+'</div>');document.body.classList.add('print-pack');},
  fieldSheet:function(m,complete){var p=m.practical;return '<section class="psheet leader-sheet field-print"><h2>'+esc(m.n)+'</h2><p><b>開場：</b>'+esc(p.opening)+'</p><p><b>分組派物：</b>'+esc(p.distribute)+'</p><p><b>唔明：</b>'+esc(p.confused)+'</p><p><b>冷場：</b>'+esc(p.quiet)+'</p><p><b>少人：</b>'+esc(p.few)+'</p><p><b>缺物資：</b>'+esc(p.missing)+'</p><p><b>縮短版：</b>'+p.short.steps.map(function(x){return x.minutes+'分鐘 '+esc(x.text);}).join('；')+'</p><p>'+esc(p.short.boundary)+'</p><p><b>觀察：</b>'+esc(m.evidence)+'</p><p><b>跟進：</b>'+esc(m.gap)+'</p><p>'+(complete?'逐節玩法與安全提示見本包前頁；問題答案與未涵蓋事項見後頁。':'完整問題答案及三步玩法在APP；本頁是現場摘要。')+'</p></section>';},
  print:function(tid){var m=Practical.meeting(tid);if(!m||!m.practical)return;Practical.printModal('領袖實戰卡',Practical.fieldSheet(m));},
  deckSheets:function(key,answers){var d=Practical.getDeck(key);if(!d)return '';var html='';for(var i=0;i<d.cards.length;i+=6)html+='<section class="psheet"><h2>'+esc(d.title)+(answers?'｜領袖答案':'｜題面')+'</h2><div class="print-card-grid">'+d.cards.slice(i,i+6).map(function(c){return '<article><h3>'+esc(c.front)+'</h3>'+(answers?'<p>'+esc(c.back)+'</p>':'<p class="mut">說出意思／配對／排序</p>')+'</article>';}).join('')+'</div></section>';return html;},
  printDeck:function(key,answers){var d=Practical.getDeck(key);if(d)Practical.printModal(d.title,Practical.deckSheets(key,answers));}
};
var Followup = {
  date:function(offset){var d=new Date();d.setDate(d.getDate()+(offset||0));return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');},
  validDate:function(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;var d=new Date(s+'T12:00:00');return !isNaN(d.getTime())&&d.getFullYear()===Number(s.slice(0,4))&&d.getMonth()+1===Number(s.slice(5,7))&&d.getDate()===Number(s.slice(8,10));},
  read:function(tid){var all=Store.get('followupNotes',{});var x=all&&typeof all==='object'?all[tid]:null;return x&&typeof x==='object'?x:{};},
  panel:function(m){var c=DATA.followupContent[m.tid];if(!c)return '';var x=Followup.read(m.tid);return '<section class="card followup-summary"><h3>📆 做完今場，仲有一次回顧</h3><p>'+esc(c.task)+'</p><p class="mut">'+(x.due?'已約 '+esc(x.due)+(x.reviewed?' · 已記錄回顧':' · 待回顧'):'尚未約回顧日期')+'</p><button class="btn" onclick="Followup.open(\''+m.tid+'\')">家庭任務・約回顧・記備忘</button></section>';},
  open:function(tid){var m=Practical.meeting(tid),c=DATA.followupContent[tid];if(!m||!c)return;var x=Followup.read(tid);Modal.open('<h2>'+esc(m.n)+'｜實踐後回顧</h2><h3>向家庭交代</h3><p>'+esc(c.task)+' 毋須拍照證明；遇到困難請告知領袖，一起調整合適支援。</p><h3>下次就問這幾句</h3><ol>'+c.questions.map(function(q){return '<li>'+esc(q)+'</li>';}).join('')+'</ol><p class="safe">'+esc(c.check)+'</p><form onsubmit="Followup.save(\''+tid+'\');return false"><label class="field-label">回顧日期<input id="followup-date" type="date" value="'+esc(x.due||Followup.date(c.days))+'" required></label><label class="field-label">領袖備忘（只記整體跟進，不記敏感個案）<textarea id="followup-note" maxlength="1000" rows="4">'+esc(x.note||'')+'</textarea></label><label><input id="followup-reviewed" type="checkbox" '+(x.reviewed?'checked':'')+'> 已進行回顧（不等於全部成員達標或獲章）</label><div class="quick"><button class="btn gr" type="submit">儲存回顧安排</button></div></form><p class="mut">只存本機；沒有自動提醒或跨APP同步。個別考驗記錄仍按旅團安排處理。</p>');},
  save:function(tid){if(!DATA.followupContent[tid])return;var date=document.getElementById('followup-date').value;if(!Followup.validDate(date)){toast('請填寫有效回顧日期');return false;}var all=Store.get('followupNotes',{});if(!all||typeof all!=='object'||Array.isArray(all))all={};all[tid]={due:date,note:String(document.getElementById('followup-note').value||'').trim().slice(0,1000),reviewed:!!document.getElementById('followup-reviewed').checked};if(!Practical.persist('followupNotes',all))return false;Modal.close();App.route();toast('✓ 已儲存回顧安排；不會自動標示獎章達標');return true;},
};
(function(){
 var prep=App.vPrep,detail=App.vMeetDetail,lead=App.vLead,book=App.vBook,act=App.activity;
 App.vPrep=function(){return Practical.summary(curMeet())+prep()+Followup.panel(curMeet());};
 App.vMeetDetail=function(m){return Practical.summary(m)+detail(m)+Followup.panel(m);};
 App.vLead=function(){return Practical.summary(curMeet())+lead();};
  App.vBook=function(){return '<section class="card"><h2>📋 開場前可直接用的文字材料</h2><div class="quick"><button class="btn" onclick="Practical.deck(\'troop\')">我的旅團四資料</button>'+Object.keys(DATA.fieldDecks).map(function(k){return '<button class="btn" onclick="Practical.deck(\''+k+'\')">'+esc(DATA.fieldDecks[k].title)+'</button>';}).join('')+'</div><p class="mut">文字材料已內置，可離線用；正式動作、圖樣及考驗要求仍需合適領袖核對。</p></section>'+book();};
 App.activity=function(tid,i){var m=Practical.meeting(tid);if(!m||!m.segs[i])return;if(!m.practical){act(tid,i);return;}var s=m.segs[i];Modal.open('<h2>'+esc(s.n)+'</h2><p class="mut">'+s.m+'分鐘 · '+esc(m.n)+'</p><p class="say">📢 '+esc(s.script)+'</p><ol class="lsteps">'+s.steps.map(function(x){return '<li>'+esc(x)+'</li>';}).join('')+'</ol><p class="safe">'+esc(s.safety)+'</p><details><summary>本節物資／觀察／節奏</summary><p>'+esc(s.mats.join('、')||'無額外物資')+'</p><p>'+esc(s.watch)+'</p><p>'+esc(s.rhythm)+'</p></details><div class="quick"><button class="btn" onclick="Practical.open(\''+tid+'\')">今場少人／冷場／缺物資點接</button><button class="btn" onclick="Practical.quiz(\''+tid+'\')">今場問題卡</button></div>');};
})();

/* A portable packet: no online detail needed once the selected text pack is printed. */
var SessionPack = {
  copies:function(n){n=Number(n);return Number.isInteger(n)&&n>=1&&n<=100?n:null;},
  panel:function(m){if(!m.practical)return '';return '<section class="card"><span class="eyebrow">選好今場 → 一包帶走</span><h2>完整出隊包</h2><p>逐節三步帶法、安全提示、實戰後備、問答答案、今場文字卡與成員工作紙一次整理。領袖頁和派發頁分開，毋須到場再上網找答案。</p><div class="quick"><button class="btn gr" onclick="SessionPack.open(\''+m.tid+'\')">整理今場完整出隊包</button><button class="btn" onclick="SessionPack.overview()">睇整套內容總覽</button></div><p class="mut">文字教材不代替所需器材、已核實實物或正式儀式指導。</p></section>';},
  open:function(tid){var m=Practical.meeting(tid);if(!m||!m.practical)return;var n=Math.min(100,Store.get('roster',[]).length||1);Modal.open('<h2>'+esc(m.n)+'｜完整出隊包</h2><p>領袖用：物資／設場／通知清單、五節完整帶法、實戰後備、問題答案及文字卡短講。派發用：題面、工作紙'+(DATA.followupContent[tid]?'及家庭任務紙':'')+'。</p><form onsubmit="SessionPack.preview(\''+tid+'\');return false"><label class="field-label">成員工作紙份數（未有名單預設1份；不打印名單）<input id="session-copies" type="number" min="1" max="100" step="1" required value="'+n+'"></label><label><input id="session-children" type="checkbox" checked> 包含派發頁（取消即只印領袖用頁）</label><div class="quick"><button class="btn gr" type="submit">產生完整列印預覽</button></div></form><p class="mut">文字題卡每套只印一組供輪流共用；需要多組可從題卡入口另印。另有精簡摘要列印，適合現場會用手機的領袖。</p>');},
  preview:function(tid){var n=SessionPack.copies(document.getElementById('session-copies').value);if(n===null){toast('請填1至100的整數份數');return false;}var m=Practical.meeting(tid);if(!m||!m.practical)return false;var children=!!document.getElementById('session-children').checked,html=SessionPack.build(m,n,children);PackPrint.activeTid=tid;Modal.open('<h2>'+esc(m.n)+'｜完整出隊包</h2><p class="mut">A4直向；領袖用頁在前，派發頁在分隔頁之後。共'+(html.match(/class="psheet/g)||[]).length+'個版面，實際頁數以打印預覽為準。取消列印不會記作已準備。</p><div class="quick"><button class="btn gr" onclick="PackPrint.doit()">列印完整出隊包</button><button class="btn" onclick="PackPrint.confirmDone()">我已印好今場教材</button><button class="btn" onclick="SessionPack.open(\''+tid+'\')">修改份數</button></div><div id="printarea">'+html+'</div>');document.body.classList.add('print-pack');return true;},
  familySheet:function(m){var c=DATA.followupContent[m.tid];if(!c)return '';var due=Followup.read(m.tid).due;return '<section class="psheet worksheet family-sheet"><h2>'+esc(m.n)+'｜帶回家的小任務</h2><p>姓名：________　開始日期：________</p><p>'+esc(c.task)+'</p><p>回顧日期：'+(Followup.validDate(due||'')?esc(due):'________（由領袖另行確認）')+'</p>'+c.questions.map(function(q){return '<div class="writing-prompt"><b>'+esc(q)+'</b><div class="writing-space"></div></div>';}).join('')+'<p>可以畫、口述或由成人代記；不要求照片、簽名或公開私人經歷。遇到困難請與領袖商量安全可行的調整。完成此紙不等於獲章。</p></section>';},
  build:function(m,n,children){if(!m||!m.practical||SessionPack.copies(n)===null)return '';var p=m.practical,decks=p.decks||[],html='<section class="psheet leader-sheet"><h2>'+esc(m.n)+'｜領袖出隊清單</h2><p>'+m.mins+'分鐘 · '+esc(m.refs.join('／'))+'</p><p><b>今場目標：</b>'+esc(m.goal)+'</p><h3>執袋（器材另備，不在紙包內）</h3><ul>'+m.bag.map(function(x){var material=DATA.materials.find(function(v){return v.n===x;});return '<li>□ '+esc(x)+(material?'：按'+n+'人估算 '+DATA.calcQty(material,n)+esc(material.unit):'：領袖按場地及人數確認')+'</li>';}).join('')+'</ul><h3>設場</h3><ul>'+m.venue.map(function(x){return '<li>□ '+esc(x)+'</li>';}).join('')+'</ul><h3>通知家庭的文字</h3><p>'+esc(m.notice)+'</p><p>集合日期／時間：________　地點：________<br>接送／取消安排：________　負責領袖：________</p><p>未確定場地、人手、器材或安全安排，不因印好本包而直接開始。</p></section>';
    m.segs.forEach(function(s,i){html+='<section class="psheet leader-sheet session-stage"><p>領袖用 · '+esc(m.n)+' · 第'+(i+1)+'／'+m.segs.length+'節</p><h2>'+esc(s.n)+'（'+s.m+'分鐘）</h2><p class="say">'+esc(s.script)+'</p><h3>跟住做</h3><ol>'+s.steps.map(function(x){return '<li>'+esc(x)+'</li>';}).join('')+'</ol><h3>物資</h3><p>'+esc(s.mats.join('、')||'無額外物資')+'</p><h3>安全與停止條件</h3><p>'+esc(s.safety)+'</p><h3>觀察／節奏</h3><p>'+esc(s.watch)+'</p><p>'+esc(s.rhythm)+'</p></section>';});
    html+=Practical.fieldSheet(m,true);
    html+='<section class="psheet leader-sheet"><h2>完場問答與領袖記錄</h2>'+p.qa.map(function(q){return '<h3>'+esc(q.q)+'</h3><p>'+esc(q.a)+'</p>';}).join('')+'<h3>觀察重點</h3><p>'+esc(m.evidence)+'</p><h3>未涵蓋／下次要跟進</h3><p>'+esc(m.gap)+'</p><h3>參與支援</h3><p>'+esc(m.adapt.easy)+'</p><p>'+esc(m.adapt.hard)+'</p><p>本次真實觀察／需要重試的步驟：________________<br>下次行動／跟進日期：________________</p><p>只記整體教學備忘；敏感個案依旅團程序另外處理。出席、工作紙與答對問題不等於獲章。</p><p>'+esc(p.sourceNote)+'</p></section>';
    decks.forEach(function(k){var d=Practical.getDeck(k);html+='<section class="psheet leader-sheet"><h2>'+esc(d.title)+'｜短講及答案</h2><p>'+esc(d.brief)+'</p>'+d.cards.map(function(c){return '<h3>'+esc(c.front)+'</h3><p>'+esc(c.back)+'</p>';}).join('')+'<p>'+(children?'以下派發區另有無答案題面。':'本次只印領袖頁；無答案題面可另行列印。')+'真實徽章及肩章圖樣仍須使用已核實實物。</p></section>';});
    if(children){html+='<section class="psheet divider"><h2>以下才派給成員</h2><p>前面的領袖帶法及答案請留起。</p><p>文字題卡：每種一組，共同使用。工作紙：'+n+'份。'+(DATA.followupContent[m.tid]?'家庭任務紙：'+n+'份。':'')+'</p><p>可以畫、口述或獲合適協助；不以填滿工作紙當作達標。</p></section>';decks.forEach(function(k){html+=Practical.deckSheets(k,false);});for(var i=0;i<n;i++){html+='<section class="psheet worksheet"><h2>'+esc(m.worksheet.title)+'</h2><p>姓名：________　小隊：________　日期：________</p>'+m.worksheet.prompts.map(function(q){return '<div class="writing-prompt"><b>'+esc(q)+'</b><div class="writing-space"></div></div>';}).join('')+'<p>可畫或口述。下次跟進日期：________　領袖觀察另記，不等於獲章。</p></section>'+SessionPack.familySheet(m);}}
    return html;
  },
  overview:function(){Modal.open('<h2>整套內容總覽</h2><p>據幼童軍訓練綱要設計，將訓練目標化成即用集會、教材與逐步帶領支援。</p><p><b>27場集會・135節帶法・27份工作紙</b><br>其中25場非森林故事集會有實戰後備、共50題問答及完整出隊包。兩場森林故事保持既有文字版。</p><h3>同一條使用路線</h3><p>選集會 → 完整出隊包／精簡列印 → 執袋 → 設場 → 逐節帶領 → 出席與真實觀察 → 需要時一週後回顧。</p><p>正式儀式、實物辨認及各章完整考驗仍須按已核對教材與合適領袖安排；沒有用出席自動換章。</p>'+DATA.meetings.filter(function(m){return m.practical;}).map(function(m){return '<details><summary>'+esc(m.n)+'</summary><p>'+esc(m.goal)+'</p><p>對應：'+esc(m.refs.join('／'))+'</p><p>仍需跟進：'+esc(m.gap)+'</p><button class="btn" onclick="SessionPack.open(\''+m.tid+'\')">開完整出隊包</button></details>';}).join('')+'<p class="mut">只有森林故事項目暫停；正式儀式及實物教材仍須完成，目前部分來源核對未結束。實地帶領須按環境調整。</p>');}
};
(function(){var pack=App.vPack,book=App.vBook,summary=Practical.summary;
 App.vPack=function(){return SessionPack.panel(curMeet())+pack();};
 Practical.summary=function(m){return summary(m)+(m.practical?'<div class="quick"><button class="btn" onclick="SessionPack.open(\''+m.tid+'\')">完整出隊包・一次印齊</button></div>':'');};
 App.vBook=function(){return '<section class="card"><h2>完整版本，一次掌握</h2><p>查看全部主題、使用路線及每場尚需實作的部分。</p><button class="btn gr" onclick="SessionPack.overview()">整套內容總覽</button></section>'+book();};
})();

/* Verified factual aids. Formal ceremony scripts remain a required open work item. */
var FormalKit = {
 sources:{uniform:'https://prog.scouting.org.hk/cub/uniform/',hats:'https://uniform.scouting.org.hk/wp-content/uploads/2017/03/uniformhandbook_p96-106.pdf',drill:'https://www.scout.org.hk/uploads/tc/circulars/16450/guidelines-of-chinese-foot-drill-and-national-flag-and-regional-flag-raising.pdf'},
 cards:[
 {id:'uniform',title:'制服實物觀察站',source:'uniform',scope:'款式與教學安排已核對；精確徽章縫製位置圖仍須完成圖像核對。',items:[['一組實物','一件幼童軍杏色恤衫、草青色短褲／裙褲、旅巾與顏色巾圈、棕色童軍皮帶、深草青色長襪、黑色無花紋繫帶鞋。男團員帽為深綠色黃間條鴨舌帽；女團員帽為深綠色圓形有邊帽。由旅團借用，不要求家庭另購兩套。'],['先排、再找、最後說','把實物放在乾淨桌面，每次一人選一件，說出名稱與一個款式特徵；再指出兩項徽章或裝備、問一個問題、畫想嘗試的活動。每組輪流使用同一套即可，不脫同伴衣物或拉扯制服。'],['看見舊資料怎樣辦','制服毛衣過渡期已於2025年9月30日結束，不再照舊頁把它列作現行制服。需要保暖時按現行童軍外套安排，並照顧個別健康需要。'],['別把紙卡當實物','名稱、顏色與用途可先教；肩章職級圖樣及縫製位置需要看清正式圖與實物。沒有實物時可先認名稱，但不能記作已完成實物辨認。']]},
 {id:'hats',title:'制服帽與肩章：準備和辨別',source:'hats',scope:'已核對制服手冊3.3文字。範圍只限幼童軍團員制服（教新領袖點樣幫幼童軍著齊）；領袖職級肩章不屬本套包範圍，亦不用帽章顏色推算肩章。',items:[['帽的使用','成員宣誓後才佩戴制服帽；室外及室內宣誓、覆誓、升旗、展旗、降旗、授旗等場合按指引佩戴。領袖亦須按安全、天氣及特殊需要調整；酷熱天氣警告期間可不用戴帽。'],['拿下後放哪裏','幼童軍帽徽向前。除帽後可用左手持著或放在適當地方；軟帽才可摺放在制服左肩帶下，不把幼童軍帽硬塞入肩帶。'],['肩章觀察要分清','成年成員依職級佩戴帽章與職級肩章，肩章套在雙肩肩帶上、緊貼肩帶末端。分辨旅團領袖肩章時，要核對職級及正式圖樣，不以制服顏色、年齡或猜測判斷。'],['現場實物分配','領袖穿戴自己的正確肩章作示範；展示另一職級時另備正式樣本，不交換穿戴冒充職級。每位成員指出一項差異再說明；展示不等同委任或晉升。']]},
 {id:'respect',title:'升旗與國歌：誰敬禮？',source:'drill',scope:'依2024年6月指引第2–3、16、23頁整理場合判斷；不是完整升降旗操作或團呼程序。',items:[['已列隊、穿整齊制服','由隊伍領袖／領隊舉手敬禮，其他隊員立正；不把「全隊一律舉手」當所有場合的固定做法。'],['沒有列隊、穿整齊制服','個別成員向旗幟舉手敬禮。童軍三指敬禮、宣誓半禮及左手握手的傳統禮節不因採用隊列動作而改變。'],['便服或制服不整齊','面向旗幟肅立致敬，不舉手敬禮。教學時先說明衣著與是否列隊，才請成員選正確做法。'],['注目禮','面向受禮者成立正姿勢，注視並目迎目送；左右轉頭不超過45度，禮畢把頭轉正。不強迫有活動限制的成員扭頸。'],['安全情境練習','領袖讀三個情境：列隊成員、獨自穿整齊制服、穿便服。每人先判斷再說原因；先用文字標示「旗的位置」練習，不使用手機音效冒充正式國歌儀式。']]},
 {id:'flags',title:'旗幟與旗架：到場檢查',source:'drill',scope:'已核對旗幟維護與展示原則；摺旗、繫旗、展旗及升降旗完整逐步程序仍屬本輪待完成項。',items:[['旗與器材另備','按當日正式安排準備團旗，或國旗及區旗；旗桿／旗架、旗繩、收納袋由旅團提供。先由成人檢查旗架穩固、繩路暢順、固定點及周邊通道，成員不攀爬或自行修理高處器材。'],['檢查旗面','保持清潔；破損、污損或褪色要更換。教學與搬運時不讓旗面拖地，不拿旗幟作遊戲地墊、遮眼布或包物料。'],['國旗與區旗並用','國旗置於顯著位置，區旗應小於國旗；列隊舉旗行進時國旗在區旗之前。左右位置須依室內／建築物外的正式觀察方向判斷，不只背「左或右」。'],['室內展示的觀察方向','背向旗幟後方牆壁、面向前方判斷左右：國旗在右、區旗在左。器材和位置未確認前不開始升掛。此檢查表不是對完整儀式已完成的簽核。']]}
 ],
 get:function(id){return FormalKit.cards.find(function(c){return c.id===id;});},
 content:function(c){return '<h2>'+esc(c.title)+'</h2>'+c.items.map(function(x){return '<h3>'+esc(x[0])+'</h3><p>'+esc(x[1])+'</p>';}).join('')+'<p class="mut">'+esc(c.scope)+'</p>';},
 open:function(id){var c=FormalKit.get(id);if(!c)return;Modal.open(FormalKit.content(c)+'<div class="quick"><button class="btn" onclick="FormalKit.print(\''+id+'\')">印這張領袖教材卡</button></div>'+extBtn(FormalKit.sources[c.source],false,'核對來源','官方文字來源；不是已完成全部儀式的聲明'));handleOffline();},
 print:function(id){var c=FormalKit.get(id);if(c)Practical.printModal(c.title,'<section class="psheet leader-sheet">'+FormalKit.content(c)+'</section>');},
 panel:function(){return '<section class="card"><h2>正式儀式與實物教材</h2><p>兩部分均列入本輪必須完成範圍，只有森林故事項目暫停。以下是已核對的實物觀察與場合判斷教材。</p><div class="quick">'+FormalKit.cards.map(function(c){return '<button class="btn" onclick="FormalKit.open(\''+c.id+'\')">'+esc(c.title)+'</button>';}).join('')+'</div><details><summary>本輪仍須完成的來源核對</summary><p>2026綱要第五章文字已核清。隊長就職／晉團及摺旗繫旗操作仍待核閱官方示範；肩章、徽章完整縫製位置與香港追蹤符號原圖留待圖片階段補核。</p><p>正式程序仍須完成；圖片按安排後補。已核對卡片不代表整套教材已完成。</p>'+extBtn(DATA.source.url,false,'新版綱要','第73–75頁：典禮與儀式')+extBtn('https://prog.scouting.org.hk/cub/ceremonies/',false,'官方儀式示範','六項示範；影片內容仍須實際核閱')+'</details></section>';}
};
(function(){var book=App.vBook,summary=Practical.summary,build=SessionPack.build;
 App.vBook=function(){return FormalKit.panel()+book();};
 Practical.summary=function(m){return summary(m)+(m.tid==='c04'?FormalKit.panel():'');};
 SessionPack.build=function(m,n,children){var html=build(m,n,children);if(!html||m.tid!=='c04')return html;var aids=FormalKit.cards.map(function(c){return '<section class="psheet leader-sheet">'+FormalKit.content(c)+'</section>';}).join(''),marker='<section class="psheet divider">';return html.includes(marker)?html.replace(marker,aids+marker):html+aids;};
})();
